// Files generated by Verilator
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VParallelLoadShiftReg.h"
// Needed for the exposed public fields via "*verilator public*"
// and Top module
#include "VParallelLoadShiftReg__Syms.h"

// Test bench files
#include "module.h"

unsigned long int wordToByteAddr(unsigned long int wordaddr)
{
    return wordaddr * 4;
}

int step(int timeStep, TESTBENCH<VParallelLoadShiftReg> *tb, VParallelLoadShiftReg___024root *top)
{
    tb->eval();
    tb->dump(timeStep);

    timeStep++;

    if (timeStep % 10 == 0)
        top->clk ^= 1;
    return timeStep;
}

void abort(TESTBENCH<VParallelLoadShiftReg> *tb)
{
    tb->shutdown();

    delete tb;

    exit(EXIT_FAILURE);
}
