// Files generated by Verilator
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VMux4.h"
// Needed for the exposed public fields via "*verilator public*"
// and Top module
#include "VMux4__Syms.h"

// Test bench files
#include "module.h"

unsigned long int wordToByteAddr(unsigned long int wordaddr)
{
    return wordaddr * 4;
}

int step(int timeStep, TESTBENCH<VMux4> *tb, VMux4___024root *top)
{
    tb->eval();
    tb->dump(timeStep);

    timeStep++;

    return timeStep;
}

void abort(TESTBENCH<VMux4> *tb)
{
    tb->shutdown();

    delete tb;

    exit(EXIT_FAILURE);
}
