#pragma once
#include <verilated.h>

#include "commands.h"
#include "console.h"
#include "row_indices.h"

// Files generated by Verilator
#include "VRangerRisc.h"
// Needed for the exposed public fields via "*verilator public*"
// and Top module
#include "VRangerRisc__Syms.h"
#include "VRangerRisc_Memory.h"

#include "console_module.h"

class Simulation
{
private:


public:
    Simulation();
    ~Simulation();

    int init(void);
    void update(void);

    void begin_reset(void);
    void reset(void);
    void end_reset(void);
};
