#include <stdio.h>
#include <iostream>
#include <iomanip>

// Files generated by Verilator
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VRangerRisc.h"
// Needed for the exposed public fields via "*verilator public*"
// and Top module
#include "VRangerRisc___024unit.h"
#include "VRangerRisc__Syms.h"

// Test bench files
#include "module.h"

extern bool assertionFailure;
extern unsigned long int wordToByteAddr(unsigned long int wordaddr);
extern int step(int timeStep, TESTBENCH<VRangerRisc> *tb, VRangerRisc___024root *top);

int loop(int timeStep, int baseTime, int duration,
         TESTBENCH<VRangerRisc> *tb,
         VRangerRisc___024root *top,
         VRangerRisc_RangerRisc *const irm,
         VRangerRisc___024unit *const unit)
{
    assertionFailure = false;
    using namespace std;

    cout << "(" << timeStep << ") to (" << (baseTime + duration) << ") Reset TB begin." << endl;

    while (timeStep <= baseTime + duration)
    {
        tb->eval();

        timeStep = step(timeStep, tb, top);
    }

    return timeStep;
}
